# Generated by Django 4.2.3 on 2024-02-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_experience_portfolio_category_userprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
