# Generated by Django 4.2.3 on 2024-02-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_service_social_remove_experience_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='service',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='social',
            new_name='socials',
        ),
    ]
